apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: ghcr.io/ssoxong/cc-slsa-argocd/slsa:sha-04b1496097e9311eebff5a0d16a5e6b724533326
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret  # Kubernetes에 생성한 GHCR secret
